baseURL = '/'
languageCode = 'en-us'
theme = "upstream2"
title = 'Innovation Upstream'
disableKinds = ["taxonomy","taxonomyTerm"]
relativeURLS = true
enableRobotsTXT = true

[markup]
[markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true    




